### ISSUE TITLE
sample project

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [ihcsim/kubernetes-terraform-secured#13]
Do you guys have a sample of the inputs that are required?  Not sure I am giving the right inputs.

A sample of what is required would be a good starter. 

Thanks

**Comment by ihcsim** [comment]
All the inputs that are needed by Terraform are defined in the [terraform.tfvars.sample](https://github.com/ihcsim/kubernetes-terraform-secured/blob/master/terraform.tfvars.sample) file. Per the README, make a copy of this file and named it terraform.tfvars.

**Comment by sonamsamdupkhangsar** [comment]
@ihcsim Got a cluster running.  however kubectl was not configured correctly. Will check again.

**Comment by ihcsim** [comment]
If Terraform exited without any errors, the kubeconfig will be output to a file named `.kubeconfig` in your project folder. Then you can run kubectl with
```
$ kubectl --kubeconfig=.kubeconfig get componentstatuses
```

**Comment by sonamsamdupkhangsar** [comment]
This is what I see close to the end: 

...
null_resource.client_kubeconfig (local-exec): Kubernetes master is running at https://MYIP:6443

null_resource.client_kubeconfig (local-exec): To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
null_resource.client_kubeconfig (local-exec): The connection to the server MYIP:6443 was refused - did you specify the right host or port?
null_resource.client_kubeconfig (local-exec): The connection to the server MYIP:6443 was refused - did you specify the right host or port?

Error: Error applying plan:

1 error(s) occurred:

* null_resource.client_kubeconfig: Error running command '      rm -f /Users/myusername/Documents/kubernetes-terraform-secured/.kubeconfig


I can log into the master node.  How do I debug if something is wrong.  I tried the kubectl --kubeconfig=.kubeconfig get componentstatuses like you have above.

**Comment by sonamsamdupkhangsar** [comment]
@ihcsim question on the value for this key: droplet_private_key_file.  Do I put my local computer's path to it's private key?

**Comment by ihcsim** [comment]
> 1 error(s) occurred:
> null_resource.client_kubeconfig: Error running command ' rm -f /Users/myusername/Documents/kubernetes-terraform-secured/.kubeconfig

Is that the end of the error logs? There should be more as to why the `rm -f` command failed. You can try remove [line 10 of the client.tf file](https://github.com/ihcsim/kubernetes-terraform-secured/blob/master/client.tf#L10) to see if that helps.

> question on the value for this key: droplet_private_key_file. Do I put my local computer's path to it's private key?

Yes.

**Comment by sonamsamdupkhangsar** [comment]
@ihcsim I removed line 10 from client.tf file.  This is the error:

> null_resource.client_kubeconfig (local-exec): To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
> null_resource.client_kubeconfig (local-exec): The connection to the server MYIP:6443 was refused - did you specify the right host or port?
> null_resource.client_kubeconfig (local-exec): The connection to the server MYIP:6443 was refused - did you specify the right host or port?
> 
> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * null_resource.client_kubeconfig: Error running command '      echo "apiVersion: v1
> kind

I logged into the master node.  I don't think the api server is running. I ran the following command:
  curl http://127.0.0.1:8080/version

and can't connect.

**Comment by ihcsim** [comment]
On the master node, what does `systemctl status kube-apiserver` say?

**Comment by sonamsamdupkhangsar** [comment]
Here is the output:
core@k8s-master-00 ~ $ systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-04-15 20:58:53 UTC;
     Docs: http://kubernetes.io/docs/admin/kube-apiserver/
  Process: 1621 ExecStart=/opt/k8s/bin/kube-apiserver --admission-control=NamespaceLifecycl
 Main PID: 1621 (code=exited, status=1/FAILURE)

**Comment by ihcsim** [comment]
That doesn't look like the full error message. Does it tell you why API server isn't starting up? Any useful error logs when you run `$ journalctl -e -u kube-apiserver`

**Comment by sonamsamdupkhangsar** [comment]
This is the output from `$ journalctl -e -u kube-apiserver`

> Apr 16 15:32:12 k8s-master-00 systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=1/FAILURE
> Apr 16 15:32:12 k8s-master-00 systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.
> Apr 16 15:32:18 k8s-master-00 systemd[1]: kube-apiserver.service: Service hold-off time over, scheduling restart.
> Apr 16 15:32:18 k8s-master-00 systemd[1]: kube-apiserver.service: Scheduled restart job, restart counter is at 52.
> Apr 16 15:32:18 k8s-master-00 systemd[1]: Stopped Kubernetes API Server.
> Apr 16 15:32:18 k8s-master-00 systemd[1]: Started Kubernetes API Server.
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: I0416 15:32:18.298088    2024 server.go:114] Version: v1.8.0
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: I0416 15:32:18.299075    2024 server.go:644] Initializing deserialization cache size based on 0MB limit
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: I0416 15:32:18.299243    2024 server.go:663] Initializing cache sizes based on 0MB limit
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: I0416 15:32:18.299412    2024 plugins.go:101] No cloud provider specified.
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: I0416 15:32:18.664404    2024 audit.go:182] No audit policy file provided for AdvancedAuditing, no events will be recorded.
> Apr 16 15:32:18 k8s-master-00 kube-apiserver[2024]: error while parsing encryption provider configuration file "/opt/k8s/encryption.yaml": could not obtain secret for named key key1: illegal base64 data at input byte 4
> Apr 16 15:32:18 k8s-master-00 systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=1/FAILURE
> Apr 16 15:32:18 k8s-master-00 systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.
> 
> 
> 

Does this value need to be a references to some other value in the config? I just picked a arbitrary value: 

> k8s_apiserver_encryption_key = "sonam"

**Comment by ihcsim** [comment]
The encryption key needs to be base64 encoded.

**Comment by sonamsamdupkhangsar** [comment]
On deploying the dashboard app is there a documentation on what or how to set the value for 

> lib_home

 and 

> tls_home

 as in:

> mountPath: "${lib_home}"
>           readOnly: true
>         - name: "tls"
>           mountPath: "${tls_home}".

**Comment by ihcsim** [comment]
The kubernetes YAML provided in this project is outdated. Please use the one on their [github repo](https://github.com/kubernetes/dashboard).

Also, I'm closing this issue since the original API server error is resolved. Feel free to open new issue if you encountered more problems.
